### ISSUE TITLE
Cannot import plugins?

### ISSUE THREAD

**Issue by xItsNickHD** [Minehut/PluginCollection#35]
The title is self-explanatory.

**Comment by imAero** [comment]
Explain a bit more, I don't understand what you mean. Is it to do with the GitHub or in-game?

**Comment by xItsNickHD** [comment]
Github. I go to mchostco/Host-Plugins and click import/upload, and I need push-access permission. So, meaning we can't suggest plugins etc?

@imAero

**Comment by imAero** [comment]
Fork the repository first, then add your own suggestion to it (plugin, config file for one or whatever it is) and then make a Pull Request.

**Comment by xItsNickHD** [comment]
Thankyou.

**Comment by xItsNickHD** [comment]
How do I put my commit onto a pr in mchostco/Host-Plugins?

**Comment by NEM0DoesStuff** [comment]
Its dieing #41
